### ISSUE TITLE
itk::Error: All meshes must have the same number of Edges & Vertices

### ISSUE THREAD

**Issue by RuslanKosarev** [statismo/statismo#222] opened 2015-08-17 12:14 UTC
When building a model by statismo-build-shape-model.exe, I get the following message
itk::Error: All meshes must have the same number of Edges & Vertices. how I can to overcome this limitation?

Best Regards

**Comment by arnaudgelas** [comment] 2015-08-17 12:39
All input meshes must have the same number of vertices and faces. If you get that error, it means that's not the case...
To overcome this limitation, you can deform one base mesh with the correct connectivity (with respect to others)...

Since it is not a bug in statismo, I will close this issue; and I invite you to post it on the mailing list, where it can also benefit to other users

HTH

**Closed by arnaudgelas** 2015-08-17 12:39 UTC

**Comment by chrisidefix** [comment] 2015-09-04 16:05
Thanks for the answer @arnaudgelas! Do you happen to have any recommendation how to deform such a base mesh? I (and probably many other people) mainly reconstruct meshes from segmentation (using some meshing approach). Of course these meshes do not have the same number of vertices or the same connectivity. It would be great if you could give some recommendation for preprocessing of the meshes to make them suitable for `statismo`.

**Comment by marcelluethi** [comment] 2015-09-07 06:37
@chrisidefix Statismo provides methods to establish correspondence between the meshes. You will find documentation and an [example use case ](https://github.com/statismo/statismo/wiki/cli-femur-model-example) on the wiki. 

Please post future question on the mailing list (statismo-users@googlegroup.com). The github issue page is for discussing issues with the software, and should not be used for question regarding its use.
